# -*- coding: utf-8 -*-
"""OutbreakAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CH63uU4DHtStWdkny0ctdj8eJ1rlzJ4

Purpose: Prepare the libraries and confirm the T4 GPU is ready
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import os

# Confirm we are using the T4 GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Hardware Status: Using {device}")

"""Purpose: Load our high-quality features and clean any errors"""

# Load the engineered dataset
df = pd.read_csv('/content/water_levels_global_ml.csv')

# Define our high-quality features
features = ['station_id', 'river_id', 'hour', 'month', 'alert_level',
            'minor_flood', 'major_flood', 'water_level_lag1',
            'water_level_lag2', 'rainfall_roll3']
target = 'water_level_now'

# Final Cleanup
df = df.dropna(subset=features + [target])
df = df[~df[features + [target]].isin([np.inf, -np.inf]).any(axis=1)]

# Global Normalization
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()
X_scaled = scaler_x.fit_transform(df[features])
y_scaled = scaler_y.fit_transform(df[[target]])

print(f"Ready: {len(df)} rows loaded.")

"""Purpose: Split the data so we use the most recent 20% of every station for testing"""

def create_sequences(data, target, window_size):
    X, y = [], []
    for i in range(len(data) - window_size):
        X.append(data[i:(i + window_size)])
        y.append(target[i + window_size])
    return np.array(X), np.array(y)

WINDOW_SIZE = 12 # 12 reports history
X_train_list, X_test_list = [], []
y_train_list, y_test_list = [], []

for station_id in df['station_id'].unique():
    station_df = df[df['station_id'] == station_id]
    X_station = scaler_x.transform(station_df[features])
    y_station = scaler_y.transform(station_df[[target]])
    X_s, y_s = create_sequences(X_station, y_station, WINDOW_SIZE)
    if len(X_s) < 1: continue
    split_idx = int(0.8 * len(X_s))
    X_train_list.append(X_s[:split_idx])
    X_test_list.append(X_s[split_idx:])
    y_train_list.append(y_s[:split_idx])
    y_test_list.append(y_s[split_idx:])

X_train = np.concatenate(X_train_list, axis=0)
X_test = np.concatenate(X_test_list, axis=0)
y_train = np.concatenate(y_train_list, axis=0)
y_test = np.concatenate(y_test_list, axis=0)

# Convert to Tensors for GPU
X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.float32).to(device)
X_test_t = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_t = torch.tensor(y_test, dtype=torch.float32).to(device)

print(f"Split Complete: {len(X_train)} training sequences, {len(X_test)} testing sequences.")

"""Purpose: Create the model structure"""

class FloodLSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, output_dim):
        super(FloodLSTM, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, dropout=0.2)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(device)
        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out

model = FloodLSTM(len(features), 128, 2, 1).to(device)
print(model)

"""Purpose: Train the AI on colab GPU"""

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

EPOCHS = 100
batch_size = 128
train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=batch_size, shuffle=True)

train_losses = []
print(f"Starting Training...")
for epoch in range(EPOCHS):
    model.train()
    epoch_loss = 0
    for b_x, b_y in train_loader:
        optimizer.zero_grad()
        out = model(b_x)
        loss = criterion(out, b_y)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        epoch_loss += loss.item()

    avg_loss = epoch_loss / len(train_loader)
    train_losses.append(avg_loss)
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/{EPOCHS} | Error (Loss): {avg_loss:.7f}")

plt.plot(train_losses)
plt.title("Error Reduction over 100 Epochs")
plt.show()

"""Purpose: See the real-world accuracy of the model in meters"""

model.eval()
with torch.no_grad():
    preds_scaled = model(X_test_t).cpu().numpy()
    y_true_scaled = y_test_t.cpu().numpy()

preds = scaler_y.inverse_transform(preds_scaled)
y_true = scaler_y.inverse_transform(y_true_scaled)

print("\n--- Model Performance (Meters) ---")
print(f"Mean Absolute Error: {mean_absolute_error(y_true, preds):.4f} m")
print(f"Confidence (R2 Score): {r2_score(y_true, preds):.4f}")

# Save the final brain
torch.save(model.state_dict(), 'flood_lstm_model_final.pth')
print("Model saved to: flood_lstm_model_final.pth")