# -*- coding: utf-8 -*-
"""train_TFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNRFM9Rw15_bdLhjZfaeWtr2SVa6aPdO
"""

# Install the missing dependencies
# !pip install lightning pytorch-forecasting scikit-learn

import pandas as pd
import numpy as np
import torch
import lightning.pytorch as pl

from lightning.pytorch.callbacks import EarlyStopping, LearningRateMonitor
from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.metrics import RMSE
from pytorch_forecasting.data import GroupNormalizer

import os
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, r2_score

# Ensure output directories exist
os.makedirs("model_perfomance", exist_ok=True)
os.makedirs("models", exist_ok=True)

filepath = '/content/water_levels_90_rivers_ready.csv'

if not os.path.exists(filepath):
    raise FileNotFoundError("❌ Upload your CSV file first!")

df = pd.read_csv(filepath)

# 🔒 Snapshot BEFORE any processing
original_df = df.copy()

print("✅ Data loaded:", df.shape)

# Replace inf
df = df.replace([np.inf, -np.inf], np.nan)

numeric_cols = [
    'water_level_now', 'water_level_lag1', 'water_level_lag2',
    'rainfall', 'rainfall_roll3', 'hour', 'month'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 🔍 DEBUG: Check NaNs before cleaning
print("🔍 NaNs BEFORE cleaning:")
print(df[numeric_cols].isna().sum())

# Drop rows where target is NaN
df = df.dropna(subset=["water_level_now"])

# Fill remaining
df[numeric_cols] = df[numeric_cols].fillna(0)

# Stabilize
df['water_level_now'] += np.random.uniform(0, 0.0001, size=len(df))

# Convert categorical
df['station_id'] = df['station_id'].astype(str)
df['river_id'] = df['river_id'].astype(str)

print("✅ Cleaning complete")

print("🔍 NaN check AFTER cleaning:")
print(df.isna().sum())

print("\n🔍 Inf check:")
print(np.isinf(df.select_dtypes(include=[np.number])).sum())

df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')
df = df.sort_values(['station_id', 'datetime'])
df['time_idx'] = df.groupby('station_id').cumcount()

print("✅ Time index ready")

max_encoder_length = 12

# Count BEFORE
stations_before = set(df['station_id'].unique())

df = df.groupby("station_id").filter(lambda x: len(x) > max_encoder_length)

# Count AFTER
stations_after = set(df['station_id'].unique())

removed_by_length = stations_before - stations_after

print(f"⚠️ Removed due to short length: {len(removed_by_length)} stations")
print("Examples:", list(removed_by_length)[:5])

print(f"--- Dataset Summary ---")
print(f"Rivers used: {df['river_id'].nunique()}")
print(f"Stations used: {df['station_id'].nunique()}")
print(f"Total rows: {len(df)}")

print("\n📍 Rows per station (first 10):")
print(df.groupby('station_id').size().head(10))
print("-------------------------")

# Ensure types match
original_df['station_id'] = original_df['station_id'].astype(str)
original_df['river_id'] = original_df['river_id'].astype(str)

original_stations = set(original_df['station_id'].unique())
final_stations = set(df['station_id'].unique())

original_rivers = set(original_df['river_id'].unique())
final_rivers = set(df['river_id'].unique())

missing_stations = original_stations - final_stations
missing_rivers = original_rivers - final_rivers

print("🚨 Missing Stations:", missing_stations)
print("🚨 Missing Rivers:", missing_rivers)

print(f"\nMissing Stations Count: {len(missing_stations)}")
print(f"Missing Rivers Count: {len(missing_rivers)}")

for station in list(missing_stations)[:10]:  # limit to first 10
    station_data = original_df[original_df['station_id'] == station]

    print(f"\n🔍 Station {station}")
    print(f"Total rows: {len(station_data)}")
    print(f"NaNs in target: {station_data['water_level_now'].isna().sum()}")

for river in missing_rivers:
    stations = original_df[original_df['river_id'] == river]['station_id'].unique()

    print(f"\n🌊 River {river}")
    print(f"Stations: {stations}")

    surviving = [s for s in stations if s in final_stations]
    print(f"Surviving stations: {surviving}")

max_prediction_length = 1

training_cutoff = df.groupby('station_id')['time_idx'].transform(lambda x: x.max() * 0.8)

train_data = df[df['time_idx'] <= training_cutoff]
test_data = df[df['time_idx'] > training_cutoff]

print("Train:", train_data.shape)
print("Test:", test_data.shape)

training = TimeSeriesDataSet(
    train_data,
    time_idx="time_idx",
    target="water_level_now",
    group_ids=["station_id"],

    min_encoder_length=max_encoder_length // 2,
    max_encoder_length=max_encoder_length,
    min_prediction_length=1,
    max_prediction_length=1,

    allow_missing_timesteps=True,

    static_categoricals=["station_id", "river_id"],

    time_varying_known_reals=[
        "hour", "month", "alert_level",
        "minor_flood", "major_flood", "rainfall"
    ],

    time_varying_unknown_reals=[
        "water_level_now",
        "water_level_lag1",
        "water_level_lag2",
        "rainfall_roll3"
    ],

    target_normalizer=GroupNormalizer(
        groups=["station_id"],
        transformation=None,
        center=False
    ),

    add_relative_time_idx=True,
    add_target_scales=True,
)

validation = TimeSeriesDataSet.from_dataset(
    training, test_data, predict=True, stop_randomization=True
)

print("✅ Dataset ready")

train_dataloader = training.to_dataloader(train=True, batch_size=1024, num_workers=4, pin_memory=True)
val_dataloader = validation.to_dataloader(train=False, batch_size=2048, num_workers=4, pin_memory=True)

tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.03,
    hidden_size=16,
    lstm_layers=1,           # Optimized: reduced from 2
    attention_head_size=1,   # Optimized: reduced from 4
    loss=RMSE(),
    reduce_on_plateau_patience=4,
)

# Optimization: Improve Float32 performance on newer GPUs
torch.set_float32_matmul_precision('medium')

trainer = pl.Trainer(
    max_epochs=30,           # Optimized: lower epochs for faster turnaround
    accelerator="gpu" if torch.cuda.is_available() else "cpu",
    devices=1,
    precision=32,            # Fixed: Overflow issue with '16-mixed' in TFT masking
    gradient_clip_val=0.1,
    callbacks=[
        EarlyStopping(monitor="val_loss", patience=5),
        LearningRateMonitor()
    ],
)

trainer.fit(tft, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

"""📊 MODEL EVALUATION & RESEARCH ANALYSIS"""

print("\n--- Starting Model Evaluation ---")

# 1. Load best model after training
best_model_path = trainer.checkpoint_callback.best_model_path
if best_model_path:
    tft = TemporalFusionTransformer.load_from_checkpoint(best_model_path)
    print(f"✅ Loaded best model from: {best_model_path}")

# 2. Generate Predictions
# Use 'raw' to get quantiles (P10, P50, P90 etc.)
raw_predictions = tft.predict(val_dataloader, mode="raw", return_x=True)
predictions = tft.predict(val_dataloader, mode="prediction")

# Flatten for metrics
# We collect the true values from the dataloader
y_true = torch.cat([y[0] for x, y in iter(val_dataloader)]).numpy()
y_pred = predictions.numpy()

# 3. Calculate Metrics (for Research Paper)
# Flatten to 1D to ensure compatibility with sklearn metrics
y_true_flat = y_true.flatten()
y_pred_flat = y_pred.flatten()

mae = mean_absolute_error(y_true_flat, y_pred_flat)
rmse = np.sqrt(np.mean((y_true_flat - y_pred_flat)**2))
r2 = r2_score(y_true_flat, y_pred_flat)

print(f"\n📈 Final Model Performance (Meters):")
print(f"Mean Absolute Error (MAE): {mae:.4f} m")
print(f"Root Mean Square Error (RMSE): {rmse:.4f} m")
print(f"Coefficient of Determination (R2): {r2:.4f}")

# 4. Visualization: Actual vs Predicted with Quantiles
# This is perfect for showing prediction confidence in a paper
plt.figure(figsize=(12, 6))
tft.plot_prediction(raw_predictions.x, raw_predictions.output, idx=0, add_loss_to_title=True)
plt.title("TFT Prediction Analysis: Actual vs Predicted with Quantile Confidence Bands")
plt.savefig("model_perfomance/TFT_actual_vs_pred.png")
plt.show()

# 5. Interpretability: Variable Importance
# This identifies which inputs (e.g. Rainfall) actually matter
interpretation = tft.interpret_output(raw_predictions.output, reduction="sum")
tft.plot_interpretation(interpretation)
plt.title("TFT Interpretability: Features Driving Flood Predictions")
plt.savefig("model_perfomance/TFT_feature_importance.png")
plt.show()

# 6. Save Final Model for Deployment
save_path = "models/tft_flood_model_final.pt"
torch.save(tft, save_path)
print(f"💾 Model saved to: {save_path}")

# Write raw metrics to text for the paper
with open("model_perfomance/TFT_metrics.txt", "w") as f:
    f.write(f"MAE: {mae}\nRMSE: {rmse}\nR2: {r2}")